=== abdenassar01/xml-parser-assignment/src/files/personne.xsd
<?xml version = "1.0" encoding = "UTF-8" standalone="no"?>

<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name = "Personnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Personne" maxOccurs="20" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="prenom" type="xs:string" />
                            <xs:element name="adresse" type="xs:string" />
                            <xs:element name="mail" type="xs:string" maxOccurs="5" />
                            <xs:element name="telephone" type="xs:string" maxOccurs="5" />
                        </xs:sequence>
                        <xs:attribute name="sexe">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Homme" />
                                    <xs:enumeration value="Femme" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence> 
        </xs:complexType>
    </xs:element> 
</xs:schema>

=== abdenassar01/xml-parser-assignment/src/files/personne.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- <!DOCTYPE Personnes PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "./files.dtd"> --><Personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personne.xsd">
    <?xml-stylesheet href="./personnes.xml" type="text/xsl"?>
    <Personne sexe="Femme">
        <nom>AMIMI</nom>
        <prenom>ABDENASSAR</prenom>
        <adresse>Taounate</adresse>
        <mail>abdenassaramimi@gmail.com</mail>
        <telephone>696788244</telephone>
    </Personne>

    
    <Personne sexe="Femme">
        <nom>abde</nom>
        <prenom>nassar</prenom>
        <adresse>martil</adresse>
        <mail>nassar@mail.com</mail>
        <telephone>0267152276</telephone>
    </Personne>
    
</Personnes>

=== abdenassar01/xml-parser-assignment/out/production/XML/files/personne.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- <!DOCTYPE Personnes PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "./files.dtd"> --><Personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personne.xsd">
    
    <Personne sexe="Femme">
        <nom>AMIMI</nom>
        <prenom>ABDENASSAR</prenom>
        <adresse>Taounate</adresse>
        <mail>abdenassaramimi@gmail.com</mail>
        <telephone>696788244</telephone>
    </Personne>

    <Personne sexe="Homme">
        <nom>AMIMI</nom>
        <prenom>ABDENASSAR</prenom>
        <adresse>Taounate</adresse>
        <mail>abdenassaramimi@gmail.com</mail>
        <telephone>696788244</telephone>
    </Personne> 
<Personne>
    <nom>nassar</nom>
    <prenom>kGS</prenom>
    <adresse>GDJAFJG</adresse>
    <mail>HKAGDK</mail>
    <telephone>JDKHA</telephone>
</Personne>
    <Personne><nom>nassar</nom><prenom>kGS</prenom><adresse>GDJAFJG</adresse><mail>HKAGDK</mail><telephone>JDKHA</telephone></Personne><Personne><nom>nassar</nom><prenom>kGS</prenom><adresse>GDJAFJG</adresse><mail>HKAGDK</mail><telephone>JDKHA</telephone></Personne><Personne><nom>nassar</nom><prenom>kGS</prenom><adresse>GDJAFJG</adresse><mail>HKAGDK</mail><telephone>JDKHA</telephone></Personne><Personne><nom>nassar</nom><prenom>kGS</prenom><adresse>GDJAFJG</adresse><mail>HKAGDK</mail><telephone>JDKHA</telephone></Personne>
</Personnes>
